writer:
    cleanup: True
    defaultFilePath: ''
reader:
    defaultFilePath: '/Users/saptarshibhowmik/Desktop/train.txt'
model:
    savePath: ''
    params:
        model_name: '355M'
        dataset:
        steps: '500'
        restore_from: 'fresh'
        run_name: 'run_1'
        print_every: '10'
        sample_every: '100'
        save_every: '100'
        length: '20'
        temperature: '0.6'
        include_prefix: 'False'
        nsamples: '1'